builds:
  - binary: php-fpm_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64

changelog:
  filters:
    exclude:
      - '^docs:'

archives:
  - id: default
    format: binary
  - id: targz
    format: tar.gz
